import type {
  Student,
  Course,
  ClassSchedule,
  AcademicSchedule,
  Announcement,
} from "./types";

export const currentStudent: Student = {
  id: "1",
  firstName: "Kwame",
  lastName: "Mensah",
  email: "kwame.mensah@university.edu.gh",
  phone: "+233 24 123 4567",
  studentId: "ESA/2024/0042",
  level: 200,
  program: "BSc. Economics",
  department: "Economics",
  membershipStatus: "active",
  joinDate: "2024-09-15",
};

export const courses: Course[] = [
  {
    id: "1",
    code: "ECON 201",
    name: "Microeconomics II",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Economics",
    lecturer: "Dr. Agyeman",
  },
  {
    id: "2",
    code: "ECON 203",
    name: "Macroeconomics II",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Economics",
    lecturer: "Prof. Adjei",
  },
  {
    id: "3",
    code: "ECON 205",
    name: "Mathematical Economics",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Economics",
    lecturer: "Dr. Ofori",
  },
  {
    id: "4",
    code: "STAT 201",
    name: "Statistics for Economists",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Statistics",
    lecturer: "Dr. Boateng",
  },
  {
    id: "5",
    code: "ECON 207",
    name: "History of Economic Thought",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Economics",
    lecturer: "Dr. Asante",
  },
  {
    id: "6",
    code: "ECON 202",
    name: "Monetary Economics",
    creditHours: 3,
    level: 200,
    semester: 2,
    department: "Economics",
    lecturer: "Dr. Owusu",
  },
  {
    id: "7",
    code: "ECON 204",
    name: "Public Finance",
    creditHours: 3,
    level: 200,
    semester: 2,
    department: "Economics",
    lecturer: "Prof. Mensah",
  },
  {
    id: "8",
    code: "ECON 206",
    name: "Econometrics I",
    creditHours: 3,
    level: 200,
    semester: 2,
    department: "Economics",
    lecturer: "Dr. Appiah",
  },
  {
    id: "9",
    code: "ECON 101",
    name: "Principles of Economics I",
    creditHours: 3,
    level: 100,
    semester: 1,
    department: "Economics",
    lecturer: "Dr. Amankwah",
  },
  {
    id: "10",
    code: "ECON 301",
    name: "Development Economics",
    creditHours: 3,
    level: 300,
    semester: 1,
    department: "Economics",
    lecturer: "Prof. Darko",
  },
  {
    id: "11",
    code: "ECON 401",
    name: "International Trade & Finance",
    creditHours: 3,
    level: 400,
    semester: 1,
    department: "Economics",
    lecturer: "Dr. Gyasi",
  },
];

export const classSchedules: ClassSchedule[] = [
  {
    id: "1",
    courseCode: "ECON 201",
    courseName: "Microeconomics II",
    dayOfWeek: "Monday",
    startTime: "08:00",
    endTime: "10:00",
    venue: "LT 3, Block A",
    lecturer: "Dr. Agyeman",
  },
  {
    id: "2",
    courseCode: "ECON 203",
    courseName: "Macroeconomics II",
    dayOfWeek: "Monday",
    startTime: "10:30",
    endTime: "12:30",
    venue: "LT 1, Main Hall",
    lecturer: "Prof. Adjei",
  },
  {
    id: "3",
    courseCode: "STAT 201",
    courseName: "Statistics for Economists",
    dayOfWeek: "Tuesday",
    startTime: "08:00",
    endTime: "10:00",
    venue: "LT 2, Block B",
    lecturer: "Dr. Boateng",
  },
  {
    id: "4",
    courseCode: "ECON 205",
    courseName: "Mathematical Economics",
    dayOfWeek: "Tuesday",
    startTime: "13:00",
    endTime: "15:00",
    venue: "LT 5, Block B",
    lecturer: "Dr. Ofori",
  },
  {
    id: "5",
    courseCode: "ECON 207",
    courseName: "History of Economic Thought",
    dayOfWeek: "Wednesday",
    startTime: "10:00",
    endTime: "12:00",
    venue: "LT 4, Block A",
    lecturer: "Dr. Asante",
  },
  {
    id: "6",
    courseCode: "ECON 201",
    courseName: "Microeconomics II (Tutorial)",
    dayOfWeek: "Thursday",
    startTime: "14:00",
    endTime: "16:00",
    venue: "SR 3, Economics Block",
    lecturer: "Dr. Agyeman",
  },
  {
    id: "7",
    courseCode: "ECON 203",
    courseName: "Macroeconomics II (Tutorial)",
    dayOfWeek: "Friday",
    startTime: "08:00",
    endTime: "10:00",
    venue: "SR 1, Economics Block",
    lecturer: "Prof. Adjei",
  },
];

export const academicSchedules: AcademicSchedule[] = [
  {
    id: "1",
    title: "First Semester",
    type: "semester",
    startDate: "2026-09-08",
    endDate: "2026-12-19",
    description: "Regular lectures, assignments, and coursework for Semester 1.",
  },
  {
    id: "2",
    title: "Midterm Examinations",
    type: "midterm",
    startDate: "2026-10-20",
    endDate: "2026-10-31",
    description:
      "Midterm assessments for all courses. Check your course schedule for specific dates.",
  },
  {
    id: "3",
    title: "Final Examinations",
    type: "finals",
    startDate: "2026-12-01",
    endDate: "2026-12-19",
    description:
      "End-of-semester final examinations. Ensure all coursework is submitted before exams begin.",
  },
  {
    id: "4",
    title: "Christmas Vacation",
    type: "vacation",
    startDate: "2026-12-20",
    endDate: "2027-01-12",
    description: "University break. Campus facilities may have limited access.",
  },
  {
    id: "5",
    title: "Second Semester",
    type: "semester",
    startDate: "2027-01-13",
    endDate: "2027-05-16",
    description: "Regular lectures, assignments, and coursework for Semester 2.",
  },
  {
    id: "6",
    title: "Vacation School",
    type: "vacation",
    startDate: "2027-06-02",
    endDate: "2027-07-25",
    description:
      "Optional vacation school for resit courses and additional credits.",
  },
];

export const announcements: Announcement[] = [
  {
    id: "1",
    title: "ESA General Meeting - Emergency Session",
    content:
      "All economics students are required to attend the emergency general meeting this Friday at the Main Auditorium by 4:00 PM. Attendance is mandatory. Topics include upcoming elections and semester dues.",
    author: "ESA President",
    createdAt: "2026-06-28T10:00:00Z",
    priority: "urgent",
    category: "Meeting",
  },
  {
    id: "2",
    title: "Semester Dues Payment Deadline Extended",
    content:
      "The deadline for semester dues payment has been extended to July 15th. Please make payments via MoMo to the official ESA account. Present your receipt at the ESA office for confirmation.",
    author: "Financial Secretary",
    createdAt: "2026-06-27T14:30:00Z",
    priority: "high",
    category: "Finance",
  },
  {
    id: "3",
    title: "Workshop: Financial Modelling & Data Analysis",
    content:
      "The ESA Academic Committee is organizing a hands-on workshop on Financial Modelling and Data Analysis this Saturday from 9 AM to 3 PM at the Computer Lab. Registration is free for all ESA members. Bring your laptops!",
    author: "Tech Committee",
    createdAt: "2026-06-26T09:00:00Z",
    priority: "medium",
    category: "Academic",
  },
  {
    id: "4",
    title: "Course Registration Reminder",
    content:
      "All students are reminded to complete their course registration for the upcoming semester before the deadline. Visit the academic affairs office if you have any issues.",
    author: "Academic Committee",
    createdAt: "2026-06-25T11:00:00Z",
    priority: "high",
    category: "Academic",
  },
  {
    id: "5",
    title: "ESA Sports Week Coming Up!",
    content:
      "Get ready for the annual ESA Sports Week! Events include football, basketball, volleyball, and table tennis. Registration forms available at the ESA office. Prizes for all winners!",
    author: "Sports Committee",
    createdAt: "2026-06-24T16:00:00Z",
    priority: "low",
    category: "Events",
  },
  {
    id: "6",
    title: "New Study Materials Available",
    content:
      "Past questions and lecture notes for ECON 201, ECON 203, and STAT 201 have been uploaded to the platform. Check the resources section for downloads.",
    author: "Academic Committee",
    createdAt: "2026-06-23T08:00:00Z",
    priority: "medium",
    category: "Academic",
  },
];
