import type {
  Student,
  Course,
  ClassSchedule,
  AcademicSchedule,
  Announcement,
  FinancialAidRecord,
  AdvisingSession,
  MentorshipMatch,
  OutreachEvent,
} from "./types";

export const currentStudent: Student = {
  id: "1",
  firstName: "Joseph",
  lastName: "Kollie",
  email: "joseph.kollie@smpu.edu.lr",
  phone: "+231 77 012 3456",
  studentId: "SMPU/ABBC/2024/0042",
  level: 200,
  program: "BSc. Economics",
  department: "Economics",
  college: "Arthur Barclay Business College",
  university: "Stella Maris Polytechnic University",
  membershipStatus: "active",
  joinDate: "2024-09-15",
  gpa: 3.52,
};

export const courses: Course[] = [
  {
    id: "1",
    code: "ECON 201",
    name: "Microeconomics II",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Economics",
    lecturer: "Mr. Abraham Jallah",
  },
  {
    id: "2",
    code: "ECON 203",
    name: "Macroeconomics II",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Economics",
    lecturer: "Prof. Ruth Sirleaf",
  },
  {
    id: "3",
    code: "ECON 205",
    name: "Mathematical Economics",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Economics",
    lecturer: "Dr. Emmanuel Togba",
  },
  {
    id: "4",
    code: "STAT 201",
    name: "Statistics for Economists",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Economics",
    lecturer: "Mr. Marcus Freeman",
  },
  {
    id: "5",
    code: "ECON 207",
    name: "History of Economic Thought",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Economics",
    lecturer: "Dr. Comfort Gbowee",
  },
  {
    id: "6",
    code: "ECON 202",
    name: "Monetary Economics",
    creditHours: 3,
    level: 200,
    semester: 2,
    department: "Economics",
    lecturer: "Dr. Samuel Boakai",
  },
  {
    id: "7",
    code: "ECON 204",
    name: "Public Finance",
    creditHours: 3,
    level: 200,
    semester: 2,
    department: "Economics",
    lecturer: "Prof. Grace Kamara",
  },
  {
    id: "8",
    code: "ECON 206",
    name: "Econometrics I",
    creditHours: 3,
    level: 200,
    semester: 2,
    department: "Economics",
    lecturer: "Dr. Patrick Flomo",
  },
  {
    id: "9",
    code: "ECON 101",
    name: "Principles of Economics I",
    creditHours: 3,
    level: 100,
    semester: 1,
    department: "Economics",
    lecturer: "Mr. Abraham Jallah",
  },
  {
    id: "10",
    code: "ECON 103",
    name: "Introduction to Business",
    creditHours: 3,
    level: 100,
    semester: 1,
    department: "Economics",
    lecturer: "Mrs. Josephine Dennis",
  },
  {
    id: "11",
    code: "ECON 301",
    name: "Development Economics",
    creditHours: 3,
    level: 300,
    semester: 1,
    department: "Economics",
    lecturer: "Prof. Ruth Sirleaf",
  },
  {
    id: "12",
    code: "ECON 303",
    name: "Liberian Economic Policy",
    creditHours: 3,
    level: 300,
    semester: 1,
    department: "Economics",
    lecturer: "Dr. Emmanuel Togba",
  },
  {
    id: "13",
    code: "ECON 401",
    name: "International Trade & Finance",
    creditHours: 3,
    level: 400,
    semester: 1,
    department: "Economics",
    lecturer: "Prof. Grace Kamara",
  },
  {
    id: "14",
    code: "ECON 403",
    name: "Research Methods in Economics",
    creditHours: 3,
    level: 400,
    semester: 1,
    department: "Economics",
    lecturer: "Dr. Samuel Boakai",
  },
];

export const classSchedules: ClassSchedule[] = [
  {
    id: "1",
    courseCode: "ECON 201",
    courseName: "Microeconomics II",
    dayOfWeek: "Monday",
    startTime: "08:00",
    endTime: "10:00",
    venue: "Lecture Hall 3, ABBC Building",
    lecturer: "Mr. Abraham Jallah",
  },
  {
    id: "2",
    courseCode: "ECON 203",
    courseName: "Macroeconomics II",
    dayOfWeek: "Monday",
    startTime: "10:30",
    endTime: "12:30",
    venue: "Lecture Hall 1, Main Campus",
    lecturer: "Prof. Ruth Sirleaf",
  },
  {
    id: "3",
    courseCode: "STAT 201",
    courseName: "Statistics for Economists",
    dayOfWeek: "Tuesday",
    startTime: "08:00",
    endTime: "10:00",
    venue: "Room 204, ABBC Building",
    lecturer: "Mr. Marcus Freeman",
  },
  {
    id: "4",
    courseCode: "ECON 205",
    courseName: "Mathematical Economics",
    dayOfWeek: "Tuesday",
    startTime: "13:00",
    endTime: "15:00",
    venue: "Lecture Hall 2, ABBC Building",
    lecturer: "Dr. Emmanuel Togba",
  },
  {
    id: "5",
    courseCode: "ECON 207",
    courseName: "History of Economic Thought",
    dayOfWeek: "Wednesday",
    startTime: "10:00",
    endTime: "12:00",
    venue: "Room 106, ABBC Building",
    lecturer: "Dr. Comfort Gbowee",
  },
  {
    id: "6",
    courseCode: "ECON 201",
    courseName: "Microeconomics II (Tutorial)",
    dayOfWeek: "Thursday",
    startTime: "14:00",
    endTime: "16:00",
    venue: "Seminar Room 2, ABBC Building",
    lecturer: "Mr. Abraham Jallah",
  },
  {
    id: "7",
    courseCode: "ECON 203",
    courseName: "Macroeconomics II (Tutorial)",
    dayOfWeek: "Friday",
    startTime: "08:00",
    endTime: "10:00",
    venue: "Seminar Room 1, ABBC Building",
    lecturer: "Prof. Ruth Sirleaf",
  },
];

export const academicSchedules: AcademicSchedule[] = [
  {
    id: "1",
    title: "First Semester",
    type: "semester",
    startDate: "2026-09-08",
    endDate: "2026-12-19",
    description:
      "Regular lectures, assignments, and coursework for Semester 1 at Stella Maris Polytechnic University.",
  },
  {
    id: "2",
    title: "Midterm Examinations",
    type: "midterm",
    startDate: "2026-10-20",
    endDate: "2026-10-31",
    description:
      "Midterm assessments for all courses. Check your course schedule for specific dates and venues within the ABBC Building.",
  },
  {
    id: "3",
    title: "Final Examinations",
    type: "finals",
    startDate: "2026-12-01",
    endDate: "2026-12-19",
    description:
      "End-of-semester final examinations. Ensure all coursework is submitted before exams begin.",
  },
  {
    id: "4",
    title: "Christmas Vacation",
    type: "vacation",
    startDate: "2026-12-20",
    endDate: "2027-01-12",
    description:
      "University break. Campus facilities may have limited access.",
  },
  {
    id: "5",
    title: "Second Semester",
    type: "semester",
    startDate: "2027-01-13",
    endDate: "2027-05-16",
    description:
      "Regular lectures, assignments, and coursework for Semester 2.",
  },
  {
    id: "6",
    title: "Vacation School",
    type: "vacation",
    startDate: "2027-06-02",
    endDate: "2027-07-25",
    description:
      "Optional vacation school for resit courses and additional credits.",
  },
];

export const announcements: Announcement[] = [
  {
    id: "1",
    title: "ESA General Meeting — Emergency Session",
    content:
      "All economics students within the Arthur Barclay Business College are required to attend the emergency general meeting this Friday at the ABBC Auditorium by 4:00 PM. Attendance is mandatory. Topics include upcoming elections and semester dues.",
    author: "ESA President",
    createdAt: "2026-06-28T10:00:00Z",
    priority: "urgent",
    category: "Meeting",
  },
  {
    id: "2",
    title: "Semester Dues Payment Deadline Extended",
    content:
      "The deadline for semester dues payment has been extended to July 15th. Please make payments via Orange Money or MTN Mobile Money to the official ESA account. Present your receipt at the ESA office in the ABBC Building for confirmation.",
    author: "Financial Secretary",
    createdAt: "2026-06-27T14:30:00Z",
    priority: "high",
    category: "Finance",
  },
  {
    id: "3",
    title: "Workshop: Financial Modelling & Data Analysis",
    content:
      "The ESA Academic Committee is organizing a hands-on workshop on Financial Modelling and Data Analysis this Saturday from 9 AM to 3 PM at the SMPU Computer Lab. Registration is free for all ESA members. Bring your laptops!",
    author: "Academic Committee",
    createdAt: "2026-06-26T09:00:00Z",
    priority: "medium",
    category: "Academic",
  },
  {
    id: "4",
    title: "Course Registration Reminder",
    content:
      "All students are reminded to complete their course registration for the upcoming semester before the deadline. Visit the academic affairs office at Stella Maris if you have any issues. ESA volunteers are available to assist with course planning.",
    author: "Academic Committee",
    createdAt: "2026-06-25T11:00:00Z",
    priority: "high",
    category: "Academic",
  },
  {
    id: "5",
    title: "ESA Community Outreach — Monrovia Clean-Up Drive",
    content:
      "Join the ESA community service team for our monthly outreach initiative! This month we partner with local communities in Monrovia for a neighborhood clean-up drive. Meet at the SMPU main gate at 7 AM. T-shirts provided.",
    author: "Outreach Committee",
    createdAt: "2026-06-24T16:00:00Z",
    priority: "low",
    category: "Community",
  },
  {
    id: "6",
    title: "Financial Aid Applications Now Open",
    content:
      "ESA is accepting applications for the Academic Excellence Scholarship for students with a GPA of 3.5 or above. Applications close July 10th. Forms available at the ESA office or on the platform. This is part of our commitment to reducing financial barriers to education.",
    author: "Financial Aid Committee",
    createdAt: "2026-06-23T08:00:00Z",
    priority: "medium",
    category: "Financial Aid",
  },
];

export const financialAidRecords: FinancialAidRecord[] = [
  {
    id: "1",
    studentId: "SMPU/ABBC/2024/0042",
    type: "scholarship",
    status: "approved",
    amount: 75000,
    currency: "LRD",
    semester: "2026/2027 - Semester 1",
    appliedDate: "2026-05-15",
    decisionDate: "2026-06-10",
    criteria: "Academic Excellence — GPA 3.5 and above",
    notes: "Awarded for outstanding academic performance. Covers partial tuition.",
  },
  {
    id: "2",
    studentId: "SMPU/ABBC/2024/0042",
    type: "book-allowance",
    status: "approved",
    amount: 15000,
    currency: "LRD",
    semester: "2025/2026 - Semester 2",
    appliedDate: "2026-01-20",
    decisionDate: "2026-02-05",
    criteria: "Need-based — demonstrated financial hardship",
  },
  {
    id: "3",
    studentId: "SMPU/ABBC/2024/0042",
    type: "grant",
    status: "pending",
    amount: 50000,
    currency: "LRD",
    semester: "2026/2027 - Semester 1",
    appliedDate: "2026-06-20",
    criteria: "ESA Research Grant — proposed study on Liberian agricultural trade policy",
  },
  {
    id: "4",
    studentId: "SMPU/ABBC/2024/0042",
    type: "tuition-waiver",
    status: "under-review",
    amount: 120000,
    currency: "LRD",
    semester: "2026/2027 - Semester 1",
    appliedDate: "2026-06-25",
    criteria: "Community Service Excellence — 100+ volunteer hours",
  },
];

export const advisingSessions: AdvisingSession[] = [
  {
    id: "1",
    studentId: "SMPU/ABBC/2024/0042",
    advisorName: "Dr. Comfort Gbowee",
    advisorRole: "Academic Advisor — Level 200",
    date: "2026-07-05",
    time: "10:00",
    type: "course-planning",
    status: "scheduled",
    location: "Room 108, ABBC Building",
    notes: "Discuss Semester 2 course selection and electives",
  },
  {
    id: "2",
    studentId: "SMPU/ABBC/2024/0042",
    advisorName: "ESA Academic Committee",
    advisorRole: "Peer Advisor",
    date: "2026-07-02",
    time: "14:00",
    type: "registration",
    status: "scheduled",
    location: "ESA Office, ABBC Building",
    notes: "Help with online registration system and course conflicts",
  },
  {
    id: "3",
    studentId: "SMPU/ABBC/2024/0042",
    advisorName: "Prof. Ruth Sirleaf",
    advisorRole: "Department Head",
    date: "2026-06-15",
    time: "11:00",
    type: "academic-support",
    status: "completed",
    location: "Room 210, ABBC Building",
    notes: "Reviewed midterm performance. Recommended additional tutorials for Macroeconomics II.",
  },
  {
    id: "4",
    studentId: "SMPU/ABBC/2024/0042",
    advisorName: "Mr. Thomas Cooper",
    advisorRole: "Career Services Coordinator",
    date: "2026-07-10",
    time: "09:00",
    type: "career-guidance",
    status: "scheduled",
    location: "Career Center, Main Campus",
    notes: "Explore internship opportunities with Central Bank of Liberia and local NGOs",
  },
];

export const mentorshipMatches: MentorshipMatch[] = [
  {
    id: "1",
    mentorName: "Dr. Amara Williams",
    mentorTitle: "Senior Economist",
    mentorOrganization: "Central Bank of Liberia",
    mentorExpertise: ["Monetary Policy", "Financial Regulation", "Economic Research"],
    menteeId: "SMPU/ABBC/2024/0042",
    programName: "ESA Professional Mentorship Program",
    startDate: "2026-06-01",
    endDate: "2026-12-31",
    status: "active",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2026-07-08",
  },
  {
    id: "2",
    mentorName: "Mrs. Fatu Kesselly",
    mentorTitle: "Policy Analyst",
    mentorOrganization: "Ministry of Finance & Development Planning",
    mentorExpertise: ["Public Finance", "Development Policy", "Budget Analysis"],
    menteeId: "SMPU/ABBC/2024/0042",
    programName: "Women in Economics Leadership Initiative",
    startDate: "2026-09-01",
    endDate: "2027-05-31",
    status: "upcoming",
    meetingFrequency: "Monthly",
  },
  {
    id: "3",
    mentorName: "Mr. George Weah Jr.",
    mentorTitle: "Regional Manager",
    mentorOrganization: "Ecobank Liberia",
    mentorExpertise: ["Banking", "Financial Services", "Entrepreneurship"],
    menteeId: "SMPU/ABBC/2024/0042",
    programName: "ESA Alumni Mentorship Network",
    startDate: "2026-01-15",
    endDate: "2026-05-30",
    status: "completed",
    meetingFrequency: "Bi-weekly",
  },
];

export const outreachEvents: OutreachEvent[] = [
  {
    id: "1",
    title: "Financial Literacy Workshop for Market Women",
    description:
      "ESA members teach basic budgeting, savings, and record-keeping skills to market women in the Waterside Market area of Monrovia.",
    type: "community-service",
    date: "2026-07-12",
    time: "09:00",
    location: "Waterside Market, Monrovia",
    organizer: "ESA Outreach Committee",
    capacity: 30,
    enrolled: 22,
    status: "upcoming",
  },
  {
    id: "2",
    title: "Seminar: Liberia's Path to Economic Diversification",
    description:
      "A panel discussion featuring economists, policymakers, and business leaders on strategies for diversifying Liberia's economy beyond traditional sectors.",
    type: "seminar",
    date: "2026-07-20",
    time: "14:00",
    location: "ABBC Auditorium, SMPU",
    organizer: "ESA Academic Committee",
    capacity: 150,
    enrolled: 89,
    status: "upcoming",
  },
  {
    id: "3",
    title: "Research Symposium: Student Papers on Liberian Economy",
    description:
      "Annual symposium where ESA members present original research papers on topics related to Liberia's socio-economic development. Best papers receive publication support.",
    type: "research",
    date: "2026-08-05",
    time: "10:00",
    location: "Conference Hall, Main Campus",
    organizer: "ESA Research Committee",
    capacity: 100,
    enrolled: 45,
    status: "upcoming",
  },
  {
    id: "4",
    title: "Career Networking: Meet Liberian Economists",
    description:
      "Networking event connecting ESA members with practicing economists from the Central Bank, LISGIS, World Bank Liberia, and local consulting firms.",
    type: "networking",
    date: "2026-07-25",
    time: "16:00",
    location: "Multi-Purpose Hall, SMPU",
    organizer: "ESA Career Committee",
    capacity: 80,
    enrolled: 67,
    status: "upcoming",
  },
  {
    id: "5",
    title: "Community Clean-Up Drive — Sinkor",
    description:
      "Monthly community service initiative. ESA members join residents of Sinkor to clean streets, clear gutters, and promote environmental awareness.",
    type: "community-service",
    date: "2026-06-14",
    time: "07:00",
    location: "Sinkor, Monrovia",
    organizer: "ESA Outreach Committee",
    capacity: 40,
    enrolled: 40,
    status: "completed",
  },
  {
    id: "6",
    title: "Excel & Data Analysis Workshop",
    description:
      "Hands-on workshop teaching ESA members how to use Excel and basic data analysis tools for economic research and coursework.",
    type: "workshop",
    date: "2026-06-21",
    time: "09:00",
    location: "Computer Lab, SMPU",
    organizer: "ESA Academic Committee",
    capacity: 35,
    enrolled: 35,
    status: "completed",
  },
];
