import type {
  Student,
  Course,
  AcademicSchedule,
  Announcement,
  FinancialAidRecord,
  AdvisingSession,
  MentorshipMatch,
  OutreachEvent,
} from "./types";

// Generic demo context (no real signed-in user yet — Profile is "coming soon").
// level and program drive the dashboard/schedule course-load views.
export const currentStudent: Student = {
  id: "1",
  firstName: "ESA",
  lastName: "Student",
  email: "student@smpu.edu.lr",
  phone: "",
  studentId: "SMPU/ABBC/2024/0042",
  level: 200,
  program: "BSc. Economics",
  department: "Economics",
  college: "Arthur Barclay Business College",
  university: "Stella Maris Polytechnic University",
  membershipStatus: "active",
  joinDate: "2024-09-15",
};

export const courses: Course[] = [
  // First Year — First Semester (Level 100 · 23 credits)
  {
    id: "1",
    code: "ACCT 101",
    name: "Principles of Accounting I",
    creditHours: 3,
    level: 100,
    semester: 1,
    department: "Accounting",
    prerequisite: "None",
  },
  {
    id: "2",
    code: "BLAW 101",
    name: "Business Law I",
    creditHours: 3,
    level: 100,
    semester: 1,
    department: "Business Law",
    prerequisite: "None",
  },
  {
    id: "3",
    code: "CT 101",
    name: "Introduction to Critical Thinking",
    creditHours: 3,
    level: 100,
    semester: 1,
    department: "Critical Thinking",
    prerequisite: "None",
  },
  {
    id: "4",
    code: "ECON 101",
    name: "Principles of Microeconomics I",
    creditHours: 3,
    level: 100,
    semester: 1,
    department: "Economics",
    prerequisite: "None",
  },
  {
    id: "5",
    code: "ENGL 101",
    name: "Freshman English I",
    creditHours: 3,
    level: 100,
    semester: 1,
    department: "English",
    prerequisite: "None",
  },
  {
    id: "6",
    code: "MATH 107",
    name: "Pre-Calculus Mathematics",
    creditHours: 4,
    level: 100,
    semester: 1,
    department: "Mathematics",
    prerequisite: "None",
  },
  {
    id: "7",
    code: "MGMT 101",
    name: "Principles of Management I",
    creditHours: 3,
    level: 100,
    semester: 1,
    department: "Management",
    prerequisite: "None",
  },
  {
    id: "8",
    code: "RELG 101",
    name: "Man and Morality",
    creditHours: 1,
    level: 100,
    semester: 1,
    department: "Religious Studies",
    prerequisite: "None",
  },
  // First Year — Second Semester (Level 100 · 23 credits)
  {
    id: "9",
    code: "ACCT 102",
    name: "Principles of Accounting II",
    creditHours: 3,
    level: 100,
    semester: 2,
    department: "Accounting",
    prerequisite: "ACCT 101",
  },
  {
    id: "10",
    code: "BLAW 102",
    name: "Business Law II",
    creditHours: 3,
    level: 100,
    semester: 2,
    department: "Business Law",
    prerequisite: "BLAW 101",
  },
  {
    id: "11",
    code: "CT 102",
    name: "Arguments, Logic and Truth",
    creditHours: 3,
    level: 100,
    semester: 2,
    department: "Critical Thinking",
    prerequisite: "CT 101",
  },
  {
    id: "12",
    code: "ECON 102",
    name: "Principles of Macroeconomics I",
    creditHours: 3,
    level: 100,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 101",
  },
  {
    id: "13",
    code: "ENGL 102",
    name: "Freshman English II",
    creditHours: 3,
    level: 100,
    semester: 2,
    department: "English",
    prerequisite: "ENGL 101",
  },
  {
    id: "14",
    code: "MATH 122",
    name: "Calculus I",
    creditHours: 4,
    level: 100,
    semester: 2,
    department: "Mathematics",
    prerequisite: "MATH 107",
  },
  {
    id: "15",
    code: "MGMT 102",
    name: "Principles of Management II",
    creditHours: 3,
    level: 100,
    semester: 2,
    department: "Management",
    prerequisite: "MGMT 101",
  },
  {
    id: "16",
    code: "RELG 102",
    name: "Norms & Standards and Morality",
    creditHours: 1,
    level: 100,
    semester: 2,
    department: "Religious Studies",
    prerequisite: "RELG 101",
  },
  // Sophomore Year — First Semester (Level 200 · 13 credits)
  {
    id: "17",
    code: "ECON 201",
    name: "Principles of Microeconomics II",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Economics",
    prerequisite: "ECON 102",
  },
  {
    id: "18",
    code: "ENGL 201",
    name: "Freshman English II",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "English",
    prerequisite: "ENGL 102",
  },
  {
    id: "19",
    code: "MATH 221",
    name: "Calculus I",
    creditHours: 4,
    level: 200,
    semester: 1,
    department: "Mathematics",
    prerequisite: "MATH 122",
  },
  {
    id: "20",
    code: "MGMT 201",
    name: "Marketing Management",
    creditHours: 3,
    level: 200,
    semester: 1,
    department: "Management",
    prerequisite: "MGMT 102",
  },
  // Sophomore Year — Second Semester (Level 200 · 16 credits)
  {
    id: "21",
    code: "ECON 202",
    name: "Principles of Macroeconomics II",
    creditHours: 3,
    level: 200,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 201",
  },
  {
    id: "22",
    code: "ECON 208",
    name: "Quantitative Methods for Decision-Making",
    creditHours: 3,
    level: 200,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 207",
  },
  {
    id: "23",
    code: "EDP 202",
    name: "Computer Science I",
    creditHours: 3,
    level: 200,
    semester: 2,
    department: "Computer Science",
    prerequisite: "ENGL 201",
  },
  {
    id: "24",
    code: "ENGL 202",
    name: "Sophomore English II",
    creditHours: 3,
    level: 200,
    semester: 2,
    department: "English",
    prerequisite: "ENGL 201",
  },
  {
    id: "25",
    code: "MATH 208",
    name: "Linear Algebra",
    creditHours: 4,
    level: 200,
    semester: 2,
    department: "Mathematics",
    prerequisite: "MATH 221",
  },
  // ── BSc in Economics · Arthur Barclay Business College (76 credit hours) ──
  // Junior Year — First Semester (Level 300 · 22 credits)
  {
    id: "26",
    code: "ECON 305",
    name: "Intermediate Economics Theory I (Microeconomics)",
    creditHours: 3,
    level: 300,
    semester: 1,
    department: "Economics",
    prerequisite: "ECON 202",
  },
  {
    id: "27",
    code: "EDP 301",
    name: "Computer Science II",
    creditHours: 3,
    level: 300,
    semester: 1,
    department: "Computer Science",
    prerequisite: "EDP 202",
  },
  {
    id: "28",
    code: "ENGL 301",
    name: "Advanced Communication Skills",
    creditHours: 3,
    level: 300,
    semester: 1,
    department: "English",
    prerequisite: "ENGL 202",
  },
  {
    id: "29",
    code: "ECON 311",
    name: "Intermediate Economics Theory I (Macroeconomics)",
    creditHours: 3,
    level: 300,
    semester: 1,
    department: "Economics",
    prerequisite: "MATH 221",
  },
  {
    id: "30",
    code: "MATH 301",
    name: "Calculus III",
    creditHours: 4,
    level: 300,
    semester: 1,
    department: "Mathematics",
    prerequisite: "MATH 208",
  },
  {
    id: "31",
    code: "ECON 315",
    name: "Mathematics for Economists",
    creditHours: 3,
    level: 300,
    semester: 1,
    department: "Economics",
    prerequisite: "MATH 208",
  },
  {
    id: "32",
    code: "STATS 301",
    name: "Business and Economics Statistics I",
    creditHours: 3,
    level: 300,
    semester: 1,
    department: "Statistics",
    prerequisite: "MATH 208",
  },
  // Junior Year — Second Semester (Level 300 · 18 credits)
  {
    id: "33",
    code: "ECON 312",
    name: "Intermediate Economics Theory II (Macroeconomics)",
    creditHours: 3,
    level: 300,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 311",
  },
  {
    id: "34",
    code: "ECON 306",
    name: "Intermediate Economics Theory II (Microeconomics)",
    creditHours: 3,
    level: 300,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 305",
  },
  {
    id: "35",
    code: "ECON 308",
    name: "Survey of the Liberian Economy",
    creditHours: 3,
    level: 300,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 315",
  },
  {
    id: "36",
    code: "ECON 310",
    name: "Managerial Economics",
    creditHours: 3,
    level: 300,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 315",
  },
  {
    id: "37",
    code: "ENGL 302",
    name: "Business Communication",
    creditHours: 3,
    level: 300,
    semester: 2,
    department: "English",
    prerequisite: "ENGL 301",
  },
  {
    id: "38",
    code: "STATS 302",
    name: "Business and Economics Statistics II",
    creditHours: 3,
    level: 300,
    semester: 2,
    department: "Statistics",
    prerequisite: "STATS 301",
  },
  // Senior Year — First Semester (Level 400 · 18 credits)
  {
    id: "39",
    code: "ECON 401",
    name: "Money and Banking I",
    creditHours: 3,
    level: 400,
    semester: 1,
    department: "Economics",
    prerequisite: "ECON 315",
  },
  {
    id: "40",
    code: "ECON 403",
    name: "Public Finance",
    creditHours: 3,
    level: 400,
    semester: 1,
    department: "Economics",
    prerequisite: "ECON 315",
  },
  {
    id: "41",
    code: "ECON 405",
    name: "Econometrics I",
    creditHours: 3,
    level: 400,
    semester: 1,
    department: "Economics",
    prerequisite: "ECON 312",
  },
  {
    id: "42",
    code: "ECON 409",
    name: "Topic in Economic Theory",
    creditHours: 3,
    level: 400,
    semester: 1,
    department: "Economics",
    prerequisite: "ECON 315",
  },
  {
    id: "43",
    code: "ECON 411",
    name: "Development Economics I",
    creditHours: 3,
    level: 400,
    semester: 1,
    department: "Economics",
    prerequisite: "ECON 312",
  },
  {
    id: "44",
    code: "MGMT 407",
    name: "Project Management",
    creditHours: 3,
    level: 400,
    semester: 1,
    department: "Management",
    prerequisite: "ENGL 302",
  },
  // Senior Year — Second Semester (Level 400 · 18 credits)
  {
    id: "45",
    code: "ECON 402",
    name: "Money and Banking II",
    creditHours: 3,
    level: 400,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 401",
  },
  {
    id: "46",
    code: "ECON 404",
    name: "Public Sector Economics",
    creditHours: 3,
    level: 400,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 403",
  },
  {
    id: "47",
    code: "ECON 406",
    name: "Econometrics II",
    creditHours: 3,
    level: 400,
    semester: 2,
    department: "Economics",
    prerequisite: "MATH 301",
  },
  {
    id: "48",
    code: "ECON 412",
    name: "Development Economics II",
    creditHours: 3,
    level: 400,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 411",
  },
  {
    id: "49",
    code: "ECON 418",
    name: "Labor Economics",
    creditHours: 3,
    level: 400,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 312",
  },
  {
    id: "50",
    code: "ECON 407",
    name: "International Economics",
    creditHours: 3,
    level: 400,
    semester: 2,
    department: "Economics",
    prerequisite: "ECON 312",
  },
];

/**
 * Semester I, 2026/2027, as published in the university's academic calendar.
 * Two dates in the source sheet are inconsistent and are flagged inline.
 */
export const academicSchedules: AcademicSchedule[] = [
  {
    id: "1",
    title: "Entrance Exam",
    type: "exam",
    startDate: "2026-03-23",
    endDate: "2026-07-31",
    description:
      "Entrance examinations for prospective students.",
  },
  {
    id: "2",
    title: "Re-admission of Old Students",
    type: "registration",
    startDate: "2026-07-01",
    endDate: "2026-07-31",
    description:
      "Returning students confirm their place for the new academic year.",
  },
  {
    id: "3",
    title: "Independence Day",
    type: "holiday",
    startDate: "2026-07-26",
    endDate: "2026-07-27",
    description:
      "National holiday. Falls on a Sunday and is celebrated on Monday, 27 July.",
  },
  {
    id: "4",
    title: "Orientation",
    type: "ceremony",
    startDate: "2026-08-03",
    description:
      "Orientation for incoming students, on the opening day of registration.",
  },
  {
    id: "5",
    title: "Registration",
    type: "registration",
    startDate: "2026-08-03",
    endDate: "2026-08-29",
    description:
      "Course registration for the first semester.",
  },
  {
    id: "6",
    title: "Stella Maris Day",
    type: "ceremony",
    startDate: "2026-08-15",
    description:
      "University celebration of its patronal feast.",
  },
  {
    id: "7",
    title: "Faculty & Staff Workshop",
    type: "ceremony",
    startDate: "2026-08-15",
    description:
      "Workshop for faculty and staff ahead of the semester.",
  },
  {
    id: "8",
    title: "National Flag Day",
    type: "holiday",
    startDate: "2026-08-24",
    description:
      "National holiday.",
  },
  {
    id: "9",
    title: "Commencement Convocation 2025/2026",
    type: "ceremony",
    startDate: "2026-08-28",
    description:
      "Graduation ceremony for the outgoing 2025/2026 class.",
  },
  {
    id: "10",
    title: "Classes Officially Begin",
    type: "semester",
    startDate: "2026-09-01",
    description:
      "First day of lectures for the 2026/2027 first semester.",
  },
  {
    id: "11",
    title: "Late Registration",
    type: "registration",
    startDate: "2026-09-07",
    endDate: "2026-09-11",
    description:
      "Registration remains open, with late fees applying.",
  },
  {
    id: "12",
    title: "Matriculation / Inauguration",
    type: "ceremony",
    startDate: "2026-09-11",
    description:
      "New students are formally admitted into the university.",
  },
  {
    id: "13",
    title: "Add/Drop Process",
    type: "registration",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    description:
      "Last window to add or drop courses without penalty.",
  },
  {
    id: "14",
    title: "1st Semester Mass",
    type: "ceremony",
    startDate: "2026-09-18",
    description:
      "Mass marking the opening of the semester.",
  },
  {
    id: "15",
    title: "Mid-term Exams",
    type: "midterm",
    startDate: "2026-10-12",
    endDate: "2026-10-17",
    description:
      "Mid-semester assessments across all courses.",
  },
  {
    id: "16",
    title: "All Saints Day",
    type: "holiday",
    startDate: "2026-11-01",
    description:
      "Holy Day of Obligation.",
  },
  {
    id: "17",
    title: "Thanksgiving Day",
    type: "holiday",
    startDate: "2026-11-05",
    description:
      "National holiday.",
  },
  {
    id: "18",
    title: "Sports Day",
    type: "ceremony",
    startDate: "2026-11-13",
    endDate: "2026-11-14",
    description:
      "Inter-departmental sporting events.",
  },
  {
    id: "19",
    title: "William V.S. Tubman Birthday",
    type: "holiday",
    // The sheet reads "Sunday, November 29, 2025". 29 November 2025 was a
    // Saturday; 29 November 2026 is the Sunday, and the celebrated date it
    // gives is in 2026, so the year is a typo.
    startDate: "2026-11-29",
    endDate: "2026-11-30",
    description:
      "National holiday. Falls on a Sunday and is celebrated on Monday, 30 November.",
  },
  {
    id: "20",
    title: "Final Exams",
    type: "finals",
    startDate: "2026-12-09",
    endDate: "2026-12-19",
    description:
      "End-of-semester examinations. All coursework must be submitted beforehand.",
  },
  {
    id: "21",
    title: "Submission of Grades",
    type: "deadline",
    // Two discrepancies in the sheet, left as written apart from the year:
    // it calls 10 December 2026 a Wednesday (it is a Thursday; the Wednesday
    // is the 9th), and ends "Monday, January 5, 2026" — 2026 is impossible
    // here, and in 2027 the 5th is a Tuesday while the Monday is the 4th.
    startDate: "2026-12-10",
    endDate: "2027-01-05",
    description:
      "Deadline for faculty to submit semester grades.",
  },
  {
    id: "22",
    title: "Student Course Evaluation / General Feedback Survey",
    type: "deadline",
    startDate: "2026-12-15",
    endDate: "2027-01-15",
    description:
      "Students rate their courses and give feedback on the semester.",
  },
  {
    id: "23",
    title: "Christmas Break",
    type: "vacation",
    startDate: "2026-12-22",
    endDate: "2027-01-04",
    description:
      "University break. Campus facilities may have limited access.",
  },
];

export const announcements: Announcement[] = [
  {
    id: "1",
    title: "ESA General Meeting — Emergency Session",
    content:
      "All economics students within the Arthur Barclay Business College are required to attend the emergency general meeting this Friday at the ABBC Auditorium by 4:00 PM. Attendance is mandatory. Topics include upcoming elections and semester dues.",
    author: "ESA President",
    createdAt: "2026-06-28T10:00:00Z",
    priority: "urgent",
    category: "Meeting",
  },
  {
    id: "2",
    title: "Semester Dues Payment Deadline Extended",
    content:
      "The deadline for semester dues payment has been extended to July 15th. Please make payments via Orange Money or MTN Mobile Money to the official ESA account. Present your receipt at the ESA office in the ABBC Building for confirmation.",
    author: "Financial Secretary",
    createdAt: "2026-06-27T14:30:00Z",
    priority: "high",
    category: "Finance",
  },
  {
    id: "3",
    title: "Workshop: Financial Modelling & Data Analysis",
    content:
      "The ESA Academic Committee is organizing a hands-on workshop on Financial Modelling and Data Analysis this Saturday from 9 AM to 3 PM at the SMPU Computer Lab. Registration is free for all ESA members. Bring your laptops!",
    author: "Academic Committee",
    createdAt: "2026-06-26T09:00:00Z",
    priority: "medium",
    category: "Academic",
  },
  {
    id: "4",
    title: "Course Registration Reminder",
    content:
      "All students are reminded to complete their course registration for the upcoming semester before the deadline. Visit the academic affairs office at Stella Maris if you have any issues. ESA volunteers are available to assist with course planning.",
    author: "Academic Committee",
    createdAt: "2026-06-25T11:00:00Z",
    priority: "high",
    category: "Academic",
  },
  {
    id: "5",
    title: "ESA Community Outreach — Monrovia Clean-Up Drive",
    content:
      "Join the ESA community service team for our monthly outreach initiative! This month we partner with local communities in Monrovia for a neighborhood clean-up drive. Meet at the SMPU main gate at 7 AM. T-shirts provided.",
    author: "Outreach Committee",
    createdAt: "2026-06-24T16:00:00Z",
    priority: "low",
    category: "Community",
  },
  {
    id: "6",
    title: "Financial Aid Applications Now Open",
    content:
      "ESA is accepting applications for the Academic Excellence Scholarship for students with a GPA of 3.5 or above. Applications close July 10th. Forms available at the ESA office or on the platform. This is part of our commitment to reducing financial barriers to education.",
    author: "Financial Aid Committee",
    createdAt: "2026-06-23T08:00:00Z",
    priority: "medium",
    category: "Financial Aid",
  },
];

export const financialAidRecords: FinancialAidRecord[] = [
  {
    id: "1",
    studentId: "SMPU/ABBC/2024/0042",
    type: "scholarship",
    status: "approved",
    amount: 75000,
    currency: "LRD",
    semester: "2026/2027 - Semester 1",
    appliedDate: "2026-05-15",
    decisionDate: "2026-06-10",
    criteria: "Academic Excellence — GPA 3.5 and above",
    notes: "Awarded for outstanding academic performance. Covers partial tuition.",
  },
  {
    id: "2",
    studentId: "SMPU/ABBC/2024/0042",
    type: "book-allowance",
    status: "approved",
    amount: 15000,
    currency: "LRD",
    semester: "2025/2026 - Semester 2",
    appliedDate: "2026-01-20",
    decisionDate: "2026-02-05",
    criteria: "Need-based — demonstrated financial hardship",
  },
  {
    id: "3",
    studentId: "SMPU/ABBC/2024/0042",
    type: "grant",
    status: "pending",
    amount: 50000,
    currency: "LRD",
    semester: "2026/2027 - Semester 1",
    appliedDate: "2026-06-20",
    criteria: "ESA Research Grant — proposed study on Liberian agricultural trade policy",
  },
  {
    id: "4",
    studentId: "SMPU/ABBC/2024/0042",
    type: "tuition-waiver",
    status: "under-review",
    amount: 120000,
    currency: "LRD",
    semester: "2026/2027 - Semester 1",
    appliedDate: "2026-06-25",
    criteria: "Community Service Excellence — 100+ volunteer hours",
  },
];

export const advisingSessions: AdvisingSession[] = [
  {
    id: "1",
    studentId: "SMPU/ABBC/2024/0042",
    advisorName: "Dr. Comfort Gbowee",
    advisorRole: "Academic Advisor — Level 200",
    date: "2026-07-05",
    time: "10:00",
    type: "course-planning",
    status: "scheduled",
    location: "Room 108, ABBC Building",
    notes: "Discuss Semester 2 course selection and electives",
  },
  {
    id: "2",
    studentId: "SMPU/ABBC/2024/0042",
    advisorName: "ESA Academic Committee",
    advisorRole: "Peer Advisor",
    date: "2026-07-02",
    time: "14:00",
    type: "registration",
    status: "scheduled",
    location: "ESA Office, ABBC Building",
    notes: "Help with online registration system and course conflicts",
  },
  {
    id: "3",
    studentId: "SMPU/ABBC/2024/0042",
    advisorName: "Prof. Ruth Sirleaf",
    advisorRole: "Department Head",
    date: "2026-06-15",
    time: "11:00",
    type: "academic-support",
    status: "completed",
    location: "Room 210, ABBC Building",
    notes: "Reviewed midterm performance. Recommended additional tutorials for Macroeconomics II.",
  },
  {
    id: "4",
    studentId: "SMPU/ABBC/2024/0042",
    advisorName: "Mr. Thomas Cooper",
    advisorRole: "Career Services Coordinator",
    date: "2026-07-10",
    time: "09:00",
    type: "career-guidance",
    status: "scheduled",
    location: "Career Center, Main Campus",
    notes: "Explore internship opportunities with Central Bank of Liberia and local NGOs",
  },
];

export const mentorshipMatches: MentorshipMatch[] = [
  {
    id: "1",
    mentorName: "Dr. Amara Williams",
    mentorTitle: "Senior Economist",
    mentorOrganization: "Central Bank of Liberia",
    mentorExpertise: ["Monetary Policy", "Financial Regulation", "Economic Research"],
    menteeId: "SMPU/ABBC/2024/0042",
    programName: "ESA Professional Mentorship Program",
    startDate: "2026-06-01",
    endDate: "2026-12-31",
    status: "active",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2026-07-08",
  },
  {
    id: "2",
    mentorName: "Mrs. Fatu Kesselly",
    mentorTitle: "Policy Analyst",
    mentorOrganization: "Ministry of Finance & Development Planning",
    mentorExpertise: ["Public Finance", "Development Policy", "Budget Analysis"],
    menteeId: "SMPU/ABBC/2024/0042",
    programName: "Women in Economics Leadership Initiative",
    startDate: "2026-09-01",
    endDate: "2027-05-31",
    status: "upcoming",
    meetingFrequency: "Monthly",
  },
  {
    id: "3",
    mentorName: "Mr. George Weah Jr.",
    mentorTitle: "Regional Manager",
    mentorOrganization: "Ecobank Liberia",
    mentorExpertise: ["Banking", "Financial Services", "Entrepreneurship"],
    menteeId: "SMPU/ABBC/2024/0042",
    programName: "ESA Alumni Mentorship Network",
    startDate: "2026-01-15",
    endDate: "2026-05-30",
    status: "completed",
    meetingFrequency: "Bi-weekly",
  },
];

export const outreachEvents: OutreachEvent[] = [
  {
    id: "1",
    title: "Financial Literacy Workshop for Market Women",
    description:
      "ESA members teach basic budgeting, savings, and record-keeping skills to market women in the Waterside Market area of Monrovia.",
    type: "community-service",
    date: "2026-07-12",
    time: "09:00",
    location: "Waterside Market, Monrovia",
    organizer: "ESA Outreach Committee",
    capacity: 30,
    enrolled: 22,
    status: "upcoming",
  },
  {
    id: "2",
    title: "Seminar: Liberia's Path to Economic Diversification",
    description:
      "A panel discussion featuring economists, policymakers, and business leaders on strategies for diversifying Liberia's economy beyond traditional sectors.",
    type: "seminar",
    date: "2026-07-20",
    time: "14:00",
    location: "ABBC Auditorium, SMPU",
    organizer: "ESA Academic Committee",
    capacity: 150,
    enrolled: 89,
    status: "upcoming",
  },
  {
    id: "3",
    title: "Research Symposium: Student Papers on Liberian Economy",
    description:
      "Annual symposium where ESA members present original research papers on topics related to Liberia's socio-economic development. Best papers receive publication support.",
    type: "research",
    date: "2026-08-05",
    time: "10:00",
    location: "Conference Hall, Main Campus",
    organizer: "ESA Research Committee",
    capacity: 100,
    enrolled: 45,
    status: "upcoming",
  },
  {
    id: "4",
    title: "Career Networking: Meet Liberian Economists",
    description:
      "Networking event connecting ESA members with practicing economists from the Central Bank, LISGIS, World Bank Liberia, and local consulting firms.",
    type: "networking",
    date: "2026-07-25",
    time: "16:00",
    location: "Multi-Purpose Hall, SMPU",
    organizer: "ESA Career Committee",
    capacity: 80,
    enrolled: 67,
    status: "upcoming",
  },
  {
    id: "5",
    title: "Community Clean-Up Drive — Sinkor",
    description:
      "Monthly community service initiative. ESA members join residents of Sinkor to clean streets, clear gutters, and promote environmental awareness.",
    type: "community-service",
    date: "2026-06-14",
    time: "07:00",
    location: "Sinkor, Monrovia",
    organizer: "ESA Outreach Committee",
    capacity: 40,
    enrolled: 40,
    status: "completed",
  },
  {
    id: "6",
    title: "Excel & Data Analysis Workshop",
    description:
      "Hands-on workshop teaching ESA members how to use Excel and basic data analysis tools for economic research and coursework.",
    type: "workshop",
    date: "2026-06-21",
    time: "09:00",
    location: "Computer Lab, SMPU",
    organizer: "ESA Academic Committee",
    capacity: 35,
    enrolled: 35,
    status: "completed",
  },
];
